name        = "Huguette"
license     = "MIT"
licenselink = "https://github.com/cathelijne/hugo-theme-huguette/blob/main/LICENSE"
description = "A very minimal theme for Hugo with options for classless.css and NetlifyCMS"
homepage    = "https://github.com/cathelijne/hugo-theme-huguette"
demosite    = "https://huguette.netlify.app/"
tags        = ["clean", "minimal", "simple", "classlesscss", "netlifycms", "light", "responsive"]
features    = ["classlesscss", "NetlifyCMS", "lightweight", "responsive"]

[author]
  name      = "Cathelijne Hornstra"
  homepage  = ""
  